## Script for Comparing Incorrectly Labeled Epochs

In [96]:
import numpy as np 
import pandas as pd
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib import pyplot as plt
import tkinter as tk
import glob
import pickle
from sklearn.model_selection import train_test_split, KFold
import matplotlib
matplotlib.use('QtAgg')

In [ ]:
# importing model 
with open("M2_all.pkl", "rb") as f:
    model = pickle.load(f)

In [ ]:
# importing features dataframe 
features_all = pd.read_pickle("training_features_19032026.pkl")

In [ ]:
X_zygo = features_all[["Zygo"]] 
X_corr = features_all[["Corr"]]

X_zygo = X_zygo.to_numpy()
X_zygo = np.array(X_zygo.tolist())
X_zygo = np.transpose(X_zygo, (0, 2, 1)) # setting dimensions 

X_corr = X_corr.to_numpy()
X_corr = np.array(X_corr.tolist())
X_corr = np.transpose(X_corr, (0, 2, 1)) # setting dimensions 

y_zygo = features_all["Num_Contractions_Zygo"].astype(int).to_numpy()
y_corr = features_all["Num_Contractions_Corr"].astype(int).to_numpy()

X = np.concatenate((X_zygo, X_corr), axis=0)
y = np.concatenate((y_zygo,y_corr),axis=0)       


indices = np.arange(len(X))
idx_train, idx_test = train_test_split(indices, test_size=0.2, random_state=42) # keep 20% purely for testing

In [ ]:
print(np.any(np.concatenate([y_pred_test_zygo, y_pred_test_corr]) != y_pred_test))

In [ ]:
n1 = len(X_zygo)
labels = np.where(idx_test < n1, "Zygo", "Corr")

idx_test_1 = idx_test[idx_test < n1]
idx_test_2 = idx_test[idx_test >= n1] 
X_test_zygo = X[idx_test_1]
X_test_corr = X[idx_test_2]
X_test = X[idx_test]

# get testing results 
y_pred_test_zygo = model.predict(X_test_zygo)   
y_pred_test_corr = model.predict(X_test_corr)   
y_pred_test  = model.predict(X_test)

y_pred_test_zygo = np.argmax(y_pred_test_zygo, axis=1)   
y_pred_test_corr = np.argmax(y_pred_test_corr, axis=1)   
y_pred_test = np.argmax(y_pred_test,axis=1)

# get other fields for dataframe 
row_idx = np.where(idx_test < n1, idx_test, idx_test - n1)

subjects = features_all["Subject"].to_numpy().squeeze()
subject_subset = subjects[row_idx]

epochs = features_all["Triggers_Order_Nap"].to_numpy()
epochs_subset = epochs[row_idx]

naps = features_all["Nap Number"].to_numpy()
naps_subset = naps[row_idx]
# get mismatched epoch indices where the tested indices dont equal predicted 
epoch_idx = np.where(y[idx_test] != y_pred_test)[0]

mismatched_subj = subject_subset[epoch_idx]
mismatched_epochs = epochs_subset[epoch_idx]
mismatched_naps = naps_subset[epoch_idx]
mismatched_labels = labels[epoch_idx]

Pre-Processing

In [ ]:
# making dataframe for epoch rescoring 
rescore_epochs = pd.DataFrame({
    "Subject": mismatched_subj,
    "Nap Number": mismatched_naps,
    "Triggers_Order_Nap":mismatched_epochs,
    "Label": labels[epoch_idx],
    "Prediction": y_pred_test[epoch_idx]
}, index=epoch_idx)

rescore_epochs.to_excel("rescore_epochs.xlsx", index=False)
rescore_epochs_reshape = (
    rescore_epochs
    .pivot_table(
        index=["Subject", "Nap Number", "Triggers_Order_Nap"],
        columns="Label",
        values="Prediction",
        aggfunc="first"
    )
    .rename(columns={
        "Zygo": "Prediction_Zygo",
        "Corr": "Prediction_Corr"
    })
    .reset_index()
)

In [ ]:
# making final dataframe for going through bad epochs 
rows = []
seen = set()

for _, row in rescore_epochs_reshape.iterrows():
    key = (row["Subject"], row["Nap Number"], row["Triggers_Order_Nap"])

    # skip duplicates
    if key in seen:
        continue
    seen.add(key)

    # find matching row(s) in the other dataframe
    match = features_all[
        (features_all["Subject"] == row["Subject"]) &
        (features_all["Nap Number"] == row["Nap Number"]) &
        (features_all["Triggers_Order_Nap"] == row["Triggers_Order_Nap"])
    ]

    # if there is a match, take the first one
    if not match.empty:
        match_row = match.iloc[0]

        match_zygo = match_row["Zygo"]
        match_corr = match_row["Corr"]

        pred_zygo = row["Prediction_Zygo"]
        pred_corr = row["Prediction_Corr"]

        if pd.isna(pred_zygo):
            pred_zygo = np.argmax(model.predict(np.array(match_zygo.tolist()).reshape(1, 2251,1), verbose=0))

        if pd.isna(pred_corr):
            pred_corr = np.argmax(model.predict(np.array(match_corr.tolist()).reshape(1, 2251,1), verbose=0))


        rows.append({
            "Subject": row["Subject"],
            "Nap Number": row["Nap Number"],
            "Triggers_Order_Nap": row["Triggers_Order_Nap"],
            "Prediction_Zygo": pred_zygo,
            "Prediction_Corr": pred_corr,

            # examples of fields from df_other
            "Num_Contractions_Zygo": match_row["Num_Contractions_Zygo"],
            "Num_Contractions_Corr": match_row["Num_Contractions_Corr"],
            "Zygo": match_row["Zygo"],
            "Corr": match_row["Corr"],
        })

    else:
        # if no match exists, still keep the row
        rows.append({
            "Subject": row["Subject"],
            "Nap Number": row["Nap Number"],
            "Triggers_Order_Nap": row["Triggers_Order_Nap"],
            "Label": row["Label"],
            "Prediction_Zygo": pred_zygo,
            "Prediction_Corr": pred_corr,

            "Num_Contractions_Zygo": pd.NA,
            "Num_Contractions_Corr": pd.NA,
            "Zygo": pd.NA,
            "Corr": pd.NA
        })


mismatch_df = pd.DataFrame(rows)

In [ ]:
#mismatch_df.insert(0, "Epoch", np.arange(np.shape(mismatch_df)[0])+1)
mismatch_df.head(10)
mismatch_df.to_pickle("mismatch_df.pkl")
#mismatch_df.to_excel("mismatch_df.xlsx", index=False)

In [ ]:
mismatch_df.head()

Scoring for Mismatched Epochs

In [ ]:
# load in subset of epochs 
mismatch_df = pd.read_pickle("mismatch_df.pkl")

In [ ]:
# Load in entire first state 
def load_saved_results_from_df(df):
    saved = {}

    for _, row in df.iterrows():
        key = (row["Epoch"], row["Muscle_type"])

        saved[key] = {
            "Epoch": row["Epoch"],
            "Muscle_type": row["Muscle_type"],
            "Response_start_sample": row["Response_start_sample"],
            "Response_end_sample": row["Response_end_sample"],
            "Contraction_number": row["Contraction_number"],
        }

    return saved

In [ ]:
current_index = 0 
loading = True # SET TO TRUE IF LOADING IN DATFRAME 

# data frame containing trigger infromation for epochs 
df_triggers = pd.DataFrame(columns=[
    "Epoch",
    "Muscle_type",
    "Response_start_sample",
    "Response_end_sample",
    "Contraction_number"
])

if loading: 
    df_triggers = pd.read_excel("zeynep_rescore.xlsx") # REPLACE WITH EXCEL FILE YOU WANT TO LOAD IN 


# tracking current state of scoring 
state = {
    "current_index": 0,          
    "selected_muscle": None,      
    "reset_mode": False,
    "fig": None,
    "axes": None,
    "saved_results": {},         
}


# scoring starts with no epochs 
def blank_epoch_state():
    return {
        "Corr": {"start": None, "end": None, "count": None},
        "Zygo": {"start": None, "end": None, "count": None},
    }


state["current_state"] = blank_epoch_state()

state["saved_results"] = load_saved_results_from_df(df_triggers)

In [ ]:
all_states_array = []
state["current_state"]

In [91]:
# GUI
frq = 250


# makes sure all elementsof scoring are complete 
def scoring_complete(muscle):
    
    s = state["current_state"][muscle]
    count = s["count"]
    start = s["start"]
    end = s["end"]


    if count is None:
        return False
    if count == 0:
        return True
    return start is not None and end is not None


# checks if scoring has started for muscle 
def scoring_started(muscle):
    s = state["current_state"][muscle]
    return any(v is not None for v in [s["start"], s["end"], s["count"]])


# rebuilds df based on current scores 
def update_df():
    global df_triggers

    if len(state["saved_results"]) == 0:
        df_triggers = pd.DataFrame(columns=[
            "Epoch",
            "Muscle_type",
            "Response_start_sample",
            "Response_end_sample",
            "Contraction_number"
        ])
        return

    rows = list(state["saved_results"].values())
    df_triggers = (
        pd.DataFrame(rows)
        .sort_values(["Epoch", "Muscle_type"])
        .reset_index(drop=True)
    )


def sync_one_muscle_to_saved(muscle):
    current_index = state["current_index"]
    s = state["current_state"][muscle]

    if scoring_complete(muscle):
        state["saved_results"][(current_index, muscle)] = {
            "Epoch": current_index,
            "Muscle_type": muscle,
            "Response_start_sample": s["start"],
            "Response_end_sample": s["end"],
            "Contraction_number": s["count"],
        }
    else:
        state["saved_results"].pop((current_index, muscle), None)

    update_df()


def sync_current_epoch_to_saved():
    # updates data frame for each muscle 
    sync_one_muscle_to_saved("Corr")
    sync_one_muscle_to_saved("Zygo")


# loads current state of epoch 
def load_current_epoch_state():
    global current_index, state

    
    current = blank_epoch_state()
    

    for muscle in ["Corr", "Zygo"]:
        key = (current_index, muscle)
        if key in state["saved_results"]:
            row = state["saved_results"][key]

            current[muscle]["start"] = row["Response_start_sample"] 
            current[muscle]["end"] = row["Response_end_sample"] 
            current[muscle]["count"] = row["Contraction_number"] 
 
    
  
    state["current_state"] = current
    state["selected_muscle"] = None
    state["reset_mode"] = False


# function for resetting muscle if press "r"
def reset_muscle(muscle):
    global current_index 

    state["current_state"][muscle] = {"start": None, "end": None, "count": None}
    state["saved_results"].pop((current_index, muscle), None)
    update_df()


# call when move to next epoch 
def move_epoch(step):
    global state, current_index
   
    # save anything complete before leaving current epoch
    sync_current_epoch_to_saved()
    n = len(mismatch_df)

    state["current_index"] = (state["current_index"] + step) % n
    current_index = state["current_index"] 
    load_current_epoch_state()

    # print("CURRENT DATAFRAME")
    # print(df_triggers)
    all_states_array.append(state["current_state"])
    print(all_states_array)
    
    plt.close()
    plot_figure(state["current_index"])


# generates title for muscle based on state of scoring 
def title_for_muscle(muscle):
    global state
    
    s = state["current_state"][muscle]
    count = s["count"]
    start = s["start"]
    end = s["end"]



    if scoring_complete(muscle):
        if count == 0:
            return f"{muscle}: SCORED | CONTRACTIONS=0", "green"
        return f"{muscle}: SCORED | CONTRACTIONS={count}, START={start}, END={end}", "green"

    if scoring_started(muscle):
        return f"{muscle}: UNFINISHED SCORING | CONTRACTIONS={count}, START={start}, END={end}", "black"

    return f"{muscle}: NOT SCORED","red"



def plot_figure(t):
    global state


    fig, ax = plt.subplots(2, 1, sharex=False)
    plt.subplots_adjust(hspace=0.5) 

    state["fig"] = fig
    state["axes"] = ax

    zygo = mismatch_df["Zygo"].iloc[t] 
    corr = mismatch_df["Corr"].iloc[t] 

    ymax_emg = max(np.max(np.array(list(zygo))),np.max(np.array(list(corr)))) 
    

    title_zygo,color_zygo = title_for_muscle("Zygo")
    title_corr,color_corru = title_for_muscle("Corr")

    fig.suptitle(f"Epoch {t+1}")

    # Corr subplot
    ax[0].plot(corr, color="blue", label="Corr")

    ax[0].set_ylim(-200, 200)

    ax[0].set_ylabel("Corr EMG [V]")
    ax[0].set_xlabel("Samples")
    ax[0].set_title(title_corr,color=color_corru)

    # Zygo subplot
    ax[1].plot(zygo, label="Zygo",color="black")
    ax[1].set_ylim(-200, 200)

    ax[1].set_ylabel("Zygo EMG [V]")
    ax[1].set_xlabel("Samples")
    ax[1].set_title(title_zygo,color=color_zygo)    


    fig.canvas.mpl_connect("button_press_event", on_click)
    fig.canvas.mpl_connect("key_press_event", on_key)


    plt.show()


# EVENTS
def on_click(event):
    global current_index 
    if event.inaxes is None or event.xdata is None:
        return

    ax_corr, ax_zygo = state["axes"]

    if event.inaxes == ax_corr:
        muscle = "Corr"
    elif event.inaxes == ax_zygo:
        muscle = "Zygo"
    else:
        return

    x = int(round(event.xdata))
    s = state["current_state"][muscle]
    state["selected_muscle"] = muscle

    if s["start"] is None:
        s["start"] = x
    elif s["end"] is None:
        s["end"] = x
    else:
        s["start"] = x
        s["end"] = None

    plt.close()
    plot_figure(current_index)


def on_key(event):
    global current_index
    key = event.key

    

    if key is None:
        return

    allowed_keys = {'0','1', '2', '3', '4', '5','6', '7', '8', '9'}

    # score selected muscle
    if key in allowed_keys:
        muscle = state["selected_muscle"]
        if muscle is None:
            print("Select a muscle first by clicking on its subplot.")
            return

        state["current_state"][muscle]["count"] = int(key)

        # immediately save completed state
        sync_one_muscle_to_saved(muscle)
        plt.close()
        plot_figure(current_index)

    # navigation
    elif key == "right":
        #current_index = (current_index + 1) % len(mismatch_df)  #
        move_epoch(1)

    elif key == "left":
        #current_index = (current_index - 1) % len(mismatch_df)  #
        move_epoch(-1)

    # reset mode
    elif key == "r":
        state["reset_mode"] = True
        plt.close()
        plot_figure(current_index)
 
    # reset Corr
    elif key == "c":
        if state["reset_mode"] or True:
            reset_muscle("Corr")
            state["selected_muscle"] = "Corr"
            state["reset_mode"] = False
            plt.close()
            plot_figure(current_index)
 
    # reset Zygo
    elif key == "z":
        if state["reset_mode"] or True:
            reset_muscle("Zygo")
            state["selected_muscle"] = "Zygo"
            state["reset_mode"] = False
            plt.close()
            plot_figure(current_index)
 
    # quit
    elif key in ["q", "escape"]:
        print("Quitting scorer.")
        plt.close(state["fig"])
        df_triggers.to_excel("zeynep_rescore.xlsx", index=False) # saving current state if crashes
        
 


load_current_epoch_state()
plot_figure(current_index)

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running
QCoreApplication::exec: The event loop is already running

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running

[{'Corr': {'start': 157, 'end': 1943, 'count': 0}, 'Zygo': {'start': 222, 'end': 736, 'count': 3}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1449, 'end': 1739, 'count': 1}}, {'Corr': {'start': 47, 'end': 2188, 'count': 0}, 'Zygo': {'start': 1519, 'end': 2113, 'count': 2}}, {'Corr': {'start': 661, 'end': 1110, 'count': 3}, 'Zygo': {'start': 421, 'end': 651, 'count': 2}}, {'Corr': {'start': 17, 'end': 2213, 'count': 0}, 'Zygo': {'start': 97, 'end': 2123, 'count': 0}}, {'Corr': {'start': 322, 'end': 651, 'count': 3}, 'Zygo': {'start': 7, 'end': 2223, 'count': 0}}, {'Corr': {'start': 307, 'end': 741, 'count': 4}, 'Zygo': {'start': -8, 'end': 2218, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1389, 'count': 1}, 'Zygo': {'start': 27, 'end': 2218, 'count': 0}}, {'Corr': {'start': 431, 'end': 726, 'count': 3}, 'Zygo': {'start': 177, 'end': 382, 'count': 1}}, {'Corr': {'start': 217, 'end': 611, 'count': 3}, 'Zygo': {'start': 22, 'end': 2158, 'count': 0}}, {'Corr': {'start': 32, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2233, 'count': 0}}, {'Corr': {'start': 12, 'end': 2233, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 546, 'end': 621, 'count': 1}, 'Zygo': {'start': 22, 'end': 2173, 'count': 0}}, {'Corr': {'start': 1629, 'end': 1908, 'count': 3}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 12, 'end': 2243, 'count': 0}, 'Zygo': {'start': 12, 'end': 2223, 'count': 0}}, {'Corr': {'start': 940, 'end': 2113, 'count': 4}, 'Zygo': {'start': -8, 'end': 77, 'count': 1}}, {'Corr': {'start': 267, 'end': 626, 'count': 3}, 'Zygo': {'start': -3, 'end': 2218, 'count': 0}}, {'Corr': {'start': 27, 'end': 2198, 'count': 0}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 27, 'end': 2223, 'count': 0}, 'Zygo': {'start': 12, 'end': 2163, 'count': 0}}, {'Corr': {'start': 7, 'end': 2228, 'count': 0}, 'Zygo': {'start': 32, 'end': 2223, 'count': 0}}, {'Corr': {'start': -8, 'end': 2173, 'count': 0}, 'Zygo': {'start': 486, 'end': 985, 'count': 3}}, {'Corr': {'start': 292, 'end': 1075, 'count': 4}, 'Zygo': {'start': 616, 'end': 751, 'count': 1}}, {'Corr': {'start': 362, 'end': 731, 'count': 3}, 'Zygo': {'start': -13, 'end': 2213, 'count': 0}}, {'Corr': {'start': 222, 'end': 546, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 541, 'end': 1280, 'count': 3}, 'Zygo': {'start': 267, 'end': 696, 'count': 3}}, {'Corr': {'start': 1190, 'end': 1849, 'count': 3}, 'Zygo': {'start': 2, 'end': 2208, 'count': 0}}, {'Corr': {'start': 421, 'end': 846, 'count': 3}, 'Zygo': {'start': 22, 'end': 2208, 'count': 0}}, {'Corr': {'start': 17, 'end': 2228, 'count': 0}, 'Zygo': {'start': 1534, 'end': 1669, 'count': 1}}, {'Corr': {'start': 546, 'end': 1170, 'count': 3}, 'Zygo': {'start': 2, 'end': 2243, 'count': 0}}, {'Corr': {'start': 945, 'end': 1479, 'count': 1}, 'Zygo': {'start': 811, 'end': 1384, 'count': 1}}, {'Corr': {'start': 396, 'end': 631, 'count': 2}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 307, 'end': 861, 'count': 2}, 'Zygo': {'start': 42, 'end': 2198, 'count': 0}}, {'Corr': {'start': 711, 'end': 945, 'count': 1}, 'Zygo': {'start': 486, 'end': 656, 'count': 1}}, {'Corr': {'start': 7, 'end': 2248, 'count': 0}, 'Zygo': {'start': 476, 'end': 1220, 'count': 3}}, {'Corr': {'start': 521, 'end': 811, 'count': 2}, 'Zygo': {'start': 27, 'end': 2198, 'count': 0}}, {'Corr': {'start': 352, 'end': 696, 'count': 2}, 'Zygo': {'start': 32, 'end': 2228, 'count': 0}}, {'Corr': {'start': 37, 'end': 2193, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 27, 'end': 2158, 'count': 0}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 736, 'end': 945, 'count': 1}, 'Zygo': {'start': 22, 'end': 2248, 'count': 0}}, {'Corr': {'start': -8, 'end': 2263, 'count': 0}, 'Zygo': {'start': 22, 'end': 2218, 'count': 0}}, {'Corr': {'start': 471, 'end': 1509, 'count': 4}, 'Zygo': {'start': 82, 'end': 2193, 'count': 0}}, {'Corr': {'start': 17, 'end': 2188, 'count': 0}, 'Zygo': {'start': 491, 'end': 731, 'count': 2}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 511, 'end': 671, 'count': 2}}, {'Corr': {'start': 531, 'end': 866, 'count': 2}, 'Zygo': {'start': 7, 'end': 2163, 'count': 0}}, {'Corr': {'start': 22, 'end': 2193, 'count': 0}, 'Zygo': {'start': 506, 'end': 821, 'count': 1}}, {'Corr': {'start': 910, 'end': 1120, 'count': 2}, 'Zygo': {'start': 62, 'end': 2238, 'count': 0}}, {'Corr': {'start': 22, 'end': 2128, 'count': 0}, 'Zygo': {'start': 461, 'end': 631, 'count': 2}}, {'Corr': {'start': 47, 'end': 2238, 'count': 0}, 'Zygo': {'start': -8, 'end': 2238, 'count': 0}}, {'Corr': {'start': 32, 'end': 2133, 'count': 0}, 'Zygo': {'start': 511, 'end': 965, 'count': 2}}, {'Corr': {'start': 57, 'end': 2123, 'count': 0}, 'Zygo': {'start': 307, 'end': 1145, 'count': 3}}, {'Corr': {'start': 47, 'end': 2183, 'count': 0}, 'Zygo': {'start': 22, 'end': 2198, 'count': 0}}, {'Corr': {'start': 12, 'end': 2223, 'count': 0}, 'Zygo': {'start': 17, 'end': 2238, 'count': 0}}, {'Corr': {'start': 571, 'end': 880, 'count': 3}, 'Zygo': {'start': 37, 'end': 2238, 'count': 0}}, {'Corr': {'start': 257, 'end': 676, 'count': 3}, 'Zygo': {'start': 576, 'end': 1025, 'count': 3}}, {'Corr': {'start': 382, 'end': 476, 'count': 1}, 'Zygo': {'start': 521, 'end': 915, 'count': 2}}, {'Corr': {'start': 37, 'end': 2078, 'count': 0}, 'Zygo': {'start': 441, 'end': 591, 'count': 2}}, {'Corr': {'start': 312, 'end': 511, 'count': 2}, 'Zygo': {'start': -13, 'end': 2178, 'count': 0}}, {'Corr': {'start': 846, 'end': 955, 'count': 1}, 'Zygo': {'start': 22, 'end': 2133, 'count': 0}}, {'Corr': {'start': 32, 'end': 2228, 'count': 0}, 'Zygo': {'start': 22, 'end': 2213, 'count': 0}}, {'Corr': {'start': -3, 'end': 2183, 'count': 0}, 'Zygo': {'start': 17, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 511, 'count': 1}, 'Zygo': {'start': 27, 'end': 2183, 'count': 0}}, {'Corr': {'start': 2, 'end': 2173, 'count': 0}, 'Zygo': {'start': 22, 'end': 2163, 'count': 0}}, {'Corr': {'start': 32, 'end': 2208, 'count': 0}, 'Zygo': {'start': 37, 'end': 2183, 'count': 0}}, {'Corr': {'start': 1355, 'end': 1539, 'count': 1}, 'Zygo': {'start': 42, 'end': 2163, 'count': 0}}, {'Corr': {'start': 72, 'end': 2183, 'count': 0}, 'Zygo': {'start': 52, 'end': 2158, 'count': 0}}, {'Corr': {'start': 42, 'end': 2098, 'count': 0}, 'Zygo': {'start': 541, 'end': 885, 'count': 3}}, {'Corr': {'start': 282, 'end': 446, 'count': 1}, 'Zygo': {'start': 282, 'end': 486, 'count': 1}}, {'Corr': {'start': 571, 'end': 925, 'count': 1}, 'Zygo': {'start': 566, 'end': 801, 'count': 1}}, {'Corr': {'start': 377, 'end': 551, 'count': 1}, 'Zygo': {'start': 7, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1090, 'end': 1928, 'count': 3}, 'Zygo': {'start': 1025, 'end': 1374, 'count': 1}}, {'Corr': {'start': 47, 'end': 2228, 'count': 0}, 'Zygo': {'start': 416, 'end': 905, 'count': 4}}, {'Corr': {'start': 22, 'end': 2163, 'count': 0}, 'Zygo': {'start': 486, 'end': 746, 'count': 2}}, {'Corr': {'start': 87, 'end': 2193, 'count': 0}, 'Zygo': {'start': 1524, 'end': 1594, 'count': 1}}, {'Corr': {'start': 2, 'end': 2233, 'count': 0}, 'Zygo': {'start': 1225, 'end': 1669, 'count': 4}}, {'Corr': {'start': 506, 'end': 686, 'count': 1}, 'Zygo': {'start': 476, 'end': 910, 'count': 3}}, {'Corr': {'start': 62, 'end': 2213, 'count': 0}, 'Zygo': {'start': 1494, 'end': 1709, 'count': 1}}, {'Corr': {'start': 62, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1040, 'end': 1185, 'count': 1}}, {'Corr': {'start': 1115, 'end': 1250, 'count': 1}, 'Zygo': {'start': 1379, 'end': 1509, 'count': 1}}, {'Corr': {'start': 247, 'end': 461, 'count': 1}, 'Zygo': {'start': 52, 'end': 2063, 'count': 0}}, {'Corr': {'start': 182, 'end': 511, 'count': 2}, 'Zygo': {'start': 37, 'end': 2178, 'count': 0}}, {'Corr': {'start': 252, 'end': 526, 'count': 1}, 'Zygo': {'start': 262, 'end': 476, 'count': 1}}, {'Corr': {'start': 37, 'end': 2113, 'count': 0}, 'Zygo': {'start': 17, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1993, 'end': 2083, 'count': 1}, 'Zygo': {'start': -28, 'end': 2213, 'count': 0}}, {'Corr': {'start': 1260, 'end': 1459, 'count': 1}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 42, 'end': 2203, 'count': 0}, 'Zygo': {'start': 446, 'end': 1265, 'count': 5}}, {'Corr': {'start': 801, 'end': 846, 'count': 1}, 'Zygo': {'start': 377, 'end': 631, 'count': 2}}, {'Corr': {'start': 17, 'end': 2173, 'count': 0}, 'Zygo': {'start': 42, 'end': 2268, 'count': 0}}, {'Corr': {'start': 237, 'end': 666, 'count': 4}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 816, 'end': 1180, 'count': 3}, 'Zygo': {'start': 22, 'end': 2123, 'count': 0}}, {'Corr': {'start': 37, 'end': 2173, 'count': 0}, 'Zygo': {'start': 312, 'end': 726, 'count': 3}}, {'Corr': {'start': 601, 'end': 1175, 'count': 4}, 'Zygo': {'start': 62, 'end': 2233, 'count': 0}}, {'Corr': {'start': 67, 'end': 142, 'count': 1}, 'Zygo': {'start': 67, 'end': 2203, 'count': 0}}, {'Corr': {'start': 666, 'end': 2248, 'count': 9}, 'Zygo': {'start': 1933, 'end': 2113, 'count': 2}}, {'Corr': {'start': 1235, 'end': 2043, 'count': 3}, 'Zygo': {'start': 167, 'end': 2113, 'count': 0}}, {'Corr': {'start': 446, 'end': 905, 'count': 2}, 'Zygo': {'start': 47, 'end': 2163, 'count': 0}}, {'Corr': {'start': 556, 'end': 1639, 'count': 5}, 'Zygo': {'start': 776, 'end': 1679, 'count': 4}}, {'Corr': {'start': 1424, 'end': 1424, 'count': 3}, 'Zygo': {'start': 332, 'end': 676, 'count': 2}}, {'Corr': {'start': 182, 'end': 701, 'count': 3}, 'Zygo': {'start': 1444, 'end': 1888, 'count': 3}}, {'Corr': {'start': 12, 'end': 2158, 'count': 0}, 'Zygo': {'start': 207, 'end': 726, 'count': 3}}, {'Corr': {'start': 22, 'end': 2028, 'count': 0}, 'Zygo': {'start': 27, 'end': 2178, 'count': 0}}, {'Corr': {'start': 516, 'end': 1155, 'count': 3}, 'Zygo': {'start': 327, 'end': 701, 'count': 1}}, {'Corr': {'start': 82, 'end': 2093, 'count': 0}, 'Zygo': {'start': 406, 'end': 761, 'count': 3}}, {'Corr': {'start': 32, 'end': 2073, 'count': 0}, 'Zygo': {'start': 322, 'end': 681, 'count': 3}}, {'Corr': {'start': 67, 'end': 2173, 'count': 0}, 'Zygo': {'start': 1664, 'end': 1799, 'count': 1}}, {'Corr': {'start': 681, 'end': 990, 'count': 3}, 'Zygo': {'start': 2063, 'end': 2258, 'count': 1}}, {'Corr': {'start': 147, 'end': 1285, 'count': 3}, 'Zygo': {'start': 1100, 'end': 1240, 'count': 1}}, {'Corr': {'start': 27, 'end': 2248, 'count': 0}, 'Zygo': {'start': 92, 'end': 2243, 'count': 0}}, {'Corr': {'start': 257, 'end': 761, 'count': 4}, 'Zygo': {'start': 411, 'end': 771, 'count': 3}}, {'Corr': {'start': 52, 'end': 2233, 'count': 0}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 27, 'end': 2168, 'count': 0}, 'Zygo': {'start': 57, 'end': 2228, 'count': 0}}, {'Corr': {'start': 362, 'end': 706, 'count': 3}, 'Zygo': {'start': 312, 'end': 386, 'count': 1}}, {'Corr': {'start': 436, 'end': 786, 'count': 2}, 'Zygo': {'start': 62, 'end': 2148, 'count': 0}}, {'Corr': {'start': 32, 'end': 2248, 'count': 0}, 'Zygo': {'start': 37, 'end': 2208, 'count': 0}}, {'Corr': {'start': 1594, 'end': 2093, 'count': 4}, 'Zygo': {'start': 516, 'end': 2208, 'count': 7}}, {'Corr': {'start': 192, 'end': 416, 'count': 2}, 'Zygo': {'start': 1893, 'end': 2148, 'count': 2}}, {'Corr': {'start': 1978, 'end': 2208, 'count': 2}, 'Zygo': {'start': 42, 'end': 2238, 'count': 0}}, {'Corr': {'start': 112, 'end': 2188, 'count': 0}, 'Zygo': {'start': 132, 'end': 2188, 'count': 0}}, {'Corr': {'start': 62, 'end': 2238, 'count': 0}, 'Zygo': {'start': 37, 'end': 2203, 'count': 0}}, {'Corr': {'start': 531, 'end': 925, 'count': 2}, 'Zygo': {'start': 32, 'end': 2238, 'count': 0}}, {'Corr': {'start': 1694, 'end': 2088, 'count': 2}, 'Zygo': {'start': 57, 'end': 2188, 'count': 0}}, {'Corr': {'start': 17, 'end': 2223, 'count': 0}, 'Zygo': {'start': 382, 'end': 766, 'count': 3}}, {'Corr': {'start': 726, 'end': 1015, 'count': 2}, 'Zygo': {'start': 52, 'end': 2183, 'count': 0}}, {'Corr': {'start': 391, 'end': 985, 'count': 4}, 'Zygo': {'start': -8, 'end': 2258, 'count': 0}}, {'Corr': {'start': 37, 'end': 2208, 'count': 0}, 'Zygo': {'start': 2, 'end': 2228, 'count': 0}}, {'Corr': {'start': 32, 'end': 2198, 'count': 0}, 'Zygo': {'start': -3, 'end': 2258, 'count': 0}}, {'Corr': {'start': 796, 'end': 1055, 'count': 3}, 'Zygo': {'start': 681, 'end': 930, 'count': 1}}, {'Corr': {'start': -13, 'end': 2163, 'count': 0}, 'Zygo': {'start': 32, 'end': 1315, 'count': 3}}, {'Corr': {'start': 337, 'end': 1704, 'count': 5}, 'Zygo': {'start': 37, 'end': 2243, 'count': 0}}, {'Corr': {'start': 736, 'end': 1155, 'count': 2}, 'Zygo': {'start': 985, 'end': 1245, 'count': 3}}, {'Corr': {'start': 481, 'end': 841, 'count': 4}, 'Zygo': {'start': 2073, 'end': 2168, 'count': 1}}, {'Corr': {'start': 302, 'end': 771, 'count': 4}, 'Zygo': {'start': 97, 'end': 2163, 'count': 0}}, {'Corr': {'start': 496, 'end': 826, 'count': 2}, 'Zygo': {'start': 67, 'end': 2238, 'count': 0}}, {'Corr': {'start': 127, 'end': 2203, 'count': 0}, 'Zygo': {'start': 751, 'end': 1045, 'count': 2}}, {'Corr': {'start': 900, 'end': 1419, 'count': 3}, 'Zygo': {'start': 7, 'end': 2198, 'count': 0}}, {'Corr': {'start': 262, 'end': 656, 'count': 3}, 'Zygo': {'start': 47, 'end': 2088, 'count': 0}}, {'Corr': {'start': 761, 'end': 915, 'count': 2}, 'Zygo': {'start': 17, 'end': 2223, 'count': 0}}, {'Corr': {'start': 237, 'end': 771, 'count': 3}, 'Zygo': {'start': 12, 'end': 2198, 'count': 0}}, {'Corr': {'start': 7, 'end': 2173, 'count': 0}, 'Zygo': {'start': 372, 'end': 1005, 'count': 4}}, {'Corr': {'start': 436, 'end': 841, 'count': 3}, 'Zygo': {'start': 57, 'end': 2153, 'count': 0}}, {'Corr': {'start': 287, 'end': 1025, 'count': 3}, 'Zygo': {'start': 17, 'end': 2213, 'count': 0}}, {'Corr': {'start': 751, 'end': 1205, 'count': 3}, 'Zygo': {'start': 47, 'end': 2183, 'count': 0}}, {'Corr': {'start': 12, 'end': 2253, 'count': 0}, 'Zygo': {'start': 7, 'end': 2188, 'count': 0}}, {'Corr': {'start': 32, 'end': 2143, 'count': 0}, 'Zygo': {'start': 327, 'end': 506, 'count': 2}}, {'Corr': {'start': 272, 'end': 636, 'count': 2}, 'Zygo': {'start': 72, 'end': 2233, 'count': 0}}, {'Corr': {'start': 57, 'end': 2223, 'count': 0}, 'Zygo': {'start': 312, 'end': 506, 'count': 2}}, {'Corr': {'start': 521, 'end': 915, 'count': 3}, 'Zygo': {'start': 47, 'end': 2203, 'count': 0}}, {'Corr': {'start': 122, 'end': 2068, 'count': 0}, 'Zygo': {'start': 716, 'end': 1070, 'count': 1}}, {'Corr': {'start': 22, 'end': 2038, 'count': 0}, 'Zygo': {'start': 197, 'end': 636, 'count': 3}}, {'Corr': {'start': 781, 'end': 925, 'count': 1}, 'Zygo': {'start': 856, 'end': 1549, 'count': 3}}, {'Corr': {'start': 107, 'end': 2103, 'count': 0}, 'Zygo': {'start': 262, 'end': 601, 'count': 3}}, {'Corr': {'start': 342, 'end': 681, 'count': 1}, 'Zygo': {'start': 57, 'end': 2148, 'count': 0}}, {'Corr': {'start': 27, 'end': 2153, 'count': 0}, 'Zygo': {'start': 411, 'end': 985, 'count': 4}}, {'Corr': {'start': 87, 'end': 2168, 'count': 0}, 'Zygo': {'start': 32, 'end': 2163, 'count': 0}}, {'Corr': {'start': 307, 'end': 1345, 'count': 4}, 'Zygo': {'start': -3, 'end': 781, 'count': 2}}, {'Corr': {'start': 257, 'end': 841, 'count': 3}, 'Zygo': {'start': 82, 'end': 1978, 'count': 0}}, {'Corr': {'start': 52, 'end': 2258, 'count': 0}, 'Zygo': {'start': 42, 'end': 2203, 'count': 0}}, {'Corr': {'start': 37, 'end': 187, 'count': 1}, 'Zygo': {'start': 32, 'end': 2193, 'count': 0}}, {'Corr': {'start': 406, 'end': 611, 'count': 2}, 'Zygo': {'start': 102, 'end': 2193, 'count': 0}}, {'Corr': {'start': 1000, 'end': 1185, 'count': 1}, 'Zygo': {'start': 357, 'end': 1240, 'count': 4}}, {'Corr': {'start': 391, 'end': 900, 'count': 3}, 'Zygo': {'start': 62, 'end': 2228, 'count': 0}}, {'Corr': {'start': 82, 'end': 2138, 'count': 0}, 'Zygo': {'start': 187, 'end': 866, 'count': 3}}, {'Corr': {'start': 1709, 'end': 2233, 'count': 3}, 'Zygo': {'start': 17, 'end': 2153, 'count': 0}}, {'Corr': {'start': 232, 'end': 801, 'count': 3}, 'Zygo': {'start': 32, 'end': 2138, 'count': 0}}, {'Corr': {'start': 52, 'end': 2238, 'count': 0}, 'Zygo': {'start': 297, 'end': 591, 'count': 1}}, {'Corr': {'start': 17, 'end': 2238, 'count': 0}, 'Zygo': {'start': 277, 'end': 841, 'count': 3}}, {'Corr': {'start': 17, 'end': 2268, 'count': 0}, 'Zygo': {'start': 1529, 'end': 1634, 'count': 1}}, {'Corr': {'start': 7, 'end': 2198, 'count': 0}, 'Zygo': {'start': 1439, 'end': 2093, 'count': 3}}, {'Corr': {'start': 362, 'end': 1360, 'count': 2}, 'Zygo': {'start': -13, 'end': 2248, 'count': 0}}, {'Corr': {'start': 681, 'end': 806, 'count': 1}, 'Zygo': {'start': 117, 'end': 207, 'count': 1}}, {'Corr': {'start': 1130, 'end': 1305, 'count': 1}, 'Zygo': {'start': 37, 'end': 2213, 'count': 0}}, {'Corr': {'start': 466, 'end': 801, 'count': 2}, 'Zygo': {'start': 207, 'end': 791, 'count': 3}}, {'Corr': {'start': 506, 'end': 995, 'count': 2}, 'Zygo': {'start': 347, 'end': 1095, 'count': 3}}, {'Corr': {'start': 396, 'end': 711, 'count': 3}, 'Zygo': {'start': 367, 'end': 751, 'count': 3}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 227, 'end': 751, 'count': 3}}, {'Corr': {'start': 416, 'end': 791, 'count': 2}, 'Zygo': {'start': 317, 'end': 726, 'count': 3}}, {'Corr': {'start': 257, 'end': 576, 'count': 3}, 'Zygo': {'start': 237, 'end': 1335, 'count': 3}}, {'Corr': {'start': 377, 'end': 876, 'count': 3}, 'Zygo': {'start': 391, 'end': 920, 'count': 3}}, {'Corr': {'start': 531, 'end': 890, 'count': 3}, 'Zygo': {'start': 566, 'end': 915, 'count': 3}}, {'Corr': {'start': 327, 'end': 1040, 'count': 3}, 'Zygo': {'start': 337, 'end': 1020, 'count': 4}}, {'Corr': {'start': 272, 'end': 1404, 'count': 6}, 'Zygo': {'start': 307, 'end': 1764, 'count': 7}}, {'Corr': {'start': 232, 'end': 631, 'count': 3}, 'Zygo': {'start': 232, 'end': 621, 'count': 3}}, {'Corr': {'start': 272, 'end': 1514, 'count': 2}, 'Zygo': {'start': 292, 'end': 656, 'count': 3}}, {'Corr': {'start': 77, 'end': 2158, 'count': 0}, 'Zygo': {'start': -13, 'end': 2028, 'count': 0}}, {'Corr': {'start': 37, 'end': 2033, 'count': 0}, 'Zygo': {'start': 162, 'end': 2168, 'count': 0}}, {'Corr': {'start': 252, 'end': 771, 'count': 3}, 'Zygo': {'start': 67, 'end': 2183, 'count': 0}}, {'Corr': {'start': 267, 'end': 676, 'count': 3}, 'Zygo': {'start': 97, 'end': 2023, 'count': 0}}, {'Corr': {'start': 57, 'end': 2203, 'count': 0}, 'Zygo': {'start': 102, 'end': 2158, 'count': 0}}, {'Corr': {'start': 1020, 'end': 1509, 'count': 3}, 'Zygo': {'start': 711, 'end': 866, 'count': 2}}, {'Corr': {'start': 367, 'end': 551, 'count': 2}, 'Zygo': {'start': 67, 'end': 2148, 'count': 0}}, {'Corr': {'start': 347, 'end': 721, 'count': 3}, 'Zygo': {'start': 7, 'end': 2208, 'count': 0}}, {'Corr': {'start': 47, 'end': 2198, 'count': 0}, 'Zygo': {'start': 257, 'end': 1080, 'count': 6}}, {'Corr': {'start': 32, 'end': 2203, 'count': 0}, 'Zygo': {'start': 676, 'end': 1719, 'count': 6}}, {'Corr': {'start': 187, 'end': 496, 'count': 3}, 'Zygo': {'start': 22, 'end': 2183, 'count': 0}}, {'Corr': {'start': 711, 'end': 1634, 'count': 3}, 'Zygo': {'start': 12, 'end': 2108, 'count': 0}}, {'Corr': {'start': 107, 'end': 2093, 'count': 0}, 'Zygo': {'start': 87, 'end': 2143, 'count': 0}}, {'Corr': {'start': 102, 'end': 2173, 'count': 0}, 'Zygo': {'start': 821, 'end': 1374, 'count': 3}}, {'Corr': {'start': 900, 'end': 1669, 'count': 3}, 'Zygo': {'start': 52, 'end': 2198, 'count': 0}}, {'Corr': {'start': 1040, 'end': 1734, 'count': 3}, 'Zygo': {'start': 32, 'end': 1978, 'count': 0}}, {'Corr': {'start': 142, 'end': 1993, 'count': 0}, 'Zygo': {'start': 52, 'end': 2228, 'count': 0}}, {'Corr': {'start': 67, 'end': 2148, 'count': 0}, 'Zygo': {'start': 626, 'end': 1020, 'count': 3}}, {'Corr': {'start': 52, 'end': 2098, 'count': 0}, 'Zygo': {'start': 476, 'end': 651, 'count': 1}}, {'Corr': {'start': 57, 'end': 2138, 'count': 0}, 'Zygo': {'start': 72, 'end': 2203, 'count': 0}}, {'Corr': {'start': 1125, 'end': 1315, 'count': 1}, 'Zygo': {'start': 57, 'end': 2178

QCoreApplication::exec: The event loop is already running

KeyboardInterrupt:

In [83]:
np.shape(all_states_array[:220] )

(220,)

In [92]:
df_final = pd.DataFrame(columns=[
    "Epoch",
    "Muscle_type",
    "Response_start_sample",
    "Response_end_sample",
    "Contraction_number"
], index=range(438))

epoch_ct = 1
df_ct = 0 
 

all_states_array_real = all_states_array[:218] 

for state_temp in all_states_array_real:
    row_c = {"Epoch": epoch_ct, 
    "Muscle_type": "Corr", 
    "Response_start_sample": state_temp["Corr"]["start"],
    "Response_end_sample": state_temp["Corr"]["end"],
    "Contraction_number": state_temp["Corr"]["count"]
    }

    row_z = {"Epoch": epoch_ct, 
    "Muscle_type": "Zygo", 
    "Response_start_sample": state_temp["Zygo"]["start"],
    "Response_end_sample": state_temp["Zygo"]["end"],
    "Contraction_number": state_temp["Zygo"]["count"]
    }
    
    df_final.iloc[df_ct] = row_c
    df_final.iloc[df_ct+1] = row_z


    epoch_ct+=1
    df_ct+= 2

In [95]:
df_final.head(30)

,Epoch,Muscle_type,Response_start_sample,Response_end_sample,Contraction_number
0,1,Corr,157,1943,0
1,1,Zygo,222,736,3
2,2,Corr,12,2233,0
3,2,Zygo,1449,1739,1
4,3,Corr,47,2188,0
5,3,Zygo,1519,2113,2
6,4,Corr,661,1110,3
7,4,Zygo,421,651,2
8,5,Corr,17,2213,0
9,5,Zygo,97,2123,0
10,6,Corr,322,651,3
11,6,Zygo,7,2223,0
12,7,Corr,307,741,4
13,7,Zygo,-8,2218,0
14,8,Corr,1040,1389,1
15,8,Zygo,27,2218,0
16,9,Corr,431,726,3
17,9,Zygo,177,382,1
18,10,Corr,217,611,3
19,10,Zygo,22,2158,0
20,11,Corr,32,2183,0
21,11,Zygo,22,2233,0
22,12,Corr,12,2233,0
23,12,Zygo,22,2218,0
24,13,Corr,546,621,1
25,13,Zygo,22,2173,0
26,14,Corr,1629,1908,3
27,14,Zygo,12,2223,0
28,15,Corr,12,2243,0
29,15,Zygo,12,2223,0

In [93]:
df_final.to_excel("final_scores_16042026_v3.xlsx", index=False)

In [94]:
df_triggers.head(30)

,Epoch,Muscle_type,Response_start_sample,Response_end_sample,Contraction_number
0,0,Corr,157,1943,0
1,0,Zygo,222,736,3
2,1,Corr,12,2233,0
3,1,Zygo,1449,1739,1
4,2,Corr,47,2188,0
5,2,Zygo,1519,2113,2
6,3,Corr,661,1110,3
7,3,Zygo,421,651,2
8,4,Corr,17,2213,0
9,4,Zygo,97,2123,0
10,5,Corr,322,651,3
11,5,Zygo,7,2223,0
12,6,Corr,307,741,4
13,6,Zygo,-8,2218,0
14,7,Corr,1040,1389,1
15,7,Zygo,27,2218,0
16,8,Corr,431,726,3
17,8,Zygo,177,382,1
18,9,Corr,217,611,3
19,9,Zygo,22,2158,0
20,10,Corr,32,2183,0
21,10,Zygo,22,2233,0
22,11,Corr,12,2233,0
23,11,Zygo,22,2218,0
24,12,Corr,546,621,1
25,12,Zygo,22,2173,0
26,13,Corr,1629,1908,3
27,13,Zygo,12,2223,0
28,14,Corr,12,2243,0
29,14,Zygo,12,2223,0

In [ ]:
df_triggers.to_excel("final_scores_16042026.xlsx", index=False)